server:
  port: 9500

properties:
  manager-url: http://localhost:10000
  send-jar-method: /grid-server/api/saveJar
  subtask-method: /grid-server/api/sendSubtasks
  jar-path: src/main/resources/jar/jar-file.jar
